name: shivayscreation
description: "A new Flutter project."
publish_to: 'none'  # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.2
  carousel_slider: ^5.0.0

  flutter_staggered_animations: ^1.1.1
  badges: ^3.1.2
  # Firebase dependencies

  firebase_core: ^3.12.1      # Firebase core dependency
  firebase_auth: ^5.3.4      # Firebase authentication dependency
  firebase_data_connect: ^0.1.2+5
  cloud_firestore: ^5.6.0     # Firebase Firestore dependency
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  cached_network_image: ^3.2.3
  intl: ^0.19.0
  async: 2.12.0
  grpc: ^3.2.4
  leak_tracker: 10.0.8
  material_color_utilities: 0.11.1
  pointycastle: ^3.9.1
  path: ^1.8.0
  vm_service: 14.3.1
  archive: ^3.0.0
  firebase_messaging: ^15.1.6
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.10
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.6
  http: ^1.0.0
  razorpay_flutter: ^1.4.0
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.1.0
  ndk: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/images/placeholder.png


  # Other configurations for assets and fonts (if needed)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

