// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP-QrOX_amyaCy9A7i-3UYGTLT94mkgHI',
    appId: '1:492835221543:web:acd713d549a5aaf5cf5e02',
    messagingSenderId: '492835221543',
    projectId: 'shivayscreation-new',
    authDomain: 'shivayscreation-new.firebaseapp.com',
    databaseURL: 'https://shivayscreation-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivayscreation-new.firebasestorage.app',
    measurementId: 'G-BS3ZYQPS1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZ56w6bI_x16Pz3uKQf_O0JYuV0zGkXg',
    appId: '1:492835221543:android:5c951846494fb134cf5e02',
    messagingSenderId: '492835221543',
    projectId: 'shivayscreation-new',
    databaseURL: 'https://shivayscreation-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivayscreation-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXUVUc8E3yw4KTsaGHFETfceygZr7hVMU',
    appId: '1:492835221543:ios:dde79c7b664215bdcf5e02',
    messagingSenderId: '492835221543',
    projectId: 'shivayscreation-new',
    databaseURL: 'https://shivayscreation-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivayscreation-new.firebasestorage.app',
    androidClientId: '492835221543-996nf9ck79afte3qmpm3lh9dfu8dadb4.apps.googleusercontent.com',
    iosClientId: '492835221543-jopbc8irjds05h4n9dv5viqpk0afig81.apps.googleusercontent.com',
    iosBundleId: 'com.shivayscreation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXUVUc8E3yw4KTsaGHFETfceygZr7hVMU',
    appId: '1:492835221543:ios:dde79c7b664215bdcf5e02',
    messagingSenderId: '492835221543',
    projectId: 'shivayscreation-new',
    databaseURL: 'https://shivayscreation-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivayscreation-new.firebasestorage.app',
    androidClientId: '492835221543-996nf9ck79afte3qmpm3lh9dfu8dadb4.apps.googleusercontent.com',
    iosClientId: '492835221543-jopbc8irjds05h4n9dv5viqpk0afig81.apps.googleusercontent.com',
    iosBundleId: 'com.shivayscreation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP-QrOX_amyaCy9A7i-3UYGTLT94mkgHI',
    appId: '1:492835221543:web:6574283305e6fbdccf5e02',
    messagingSenderId: '492835221543',
    projectId: 'shivayscreation-new',
    authDomain: 'shivayscreation-new.firebaseapp.com',
    databaseURL: 'https://shivayscreation-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivayscreation-new.firebasestorage.app',
    measurementId: 'G-74SHDJRDE6',
  );
}
